// @gonk/core — the foundation under one import.
//
// A convenience barrel over the two core packages: the typed tool registry
// (@gonk/tool-registry) and the five-tier scope system (@gonk/scope). It lets the
// common case be `import { ToolRegistry, createScope } from "@gonk/core"`.
//
// Explicit named re-exports (never `export *`, per the package conventions) so the
// surface is auditable and tree-shakeable. Reach for the focused package
// (@gonk/tool-registry, @gonk/scope) directly when you want a tighter dependency.

// ─── @gonk/tool-registry ─────────────────────────────────────────────────────
export {
  ToolRegistry,
  makeBaseContext,
  shape,
  passthrough,
  ToolError,
  ERROR_CODES,
  noopSink,
  consoleSink,
  inMemorySink,
  compositeSink,
  resolveApproval,
  isToolTier,
  tierRank,
} from "@gonk/tool-registry";
export type {
  Logger,
  ToolContext,
  InputChunk,
  InputAudioChunk,
  InputTextChunk,
  InputControlChunk,
  DuplexControl,
  InputRawChunk,
  DisplayBlock,
  Display,
  ToolEvent,
  ToolResult,
  ToolHandlerReturn,
  ToolHandler,
  ToolVisibility,
  ToolDefinition,
  ToolCostClass,
  ToolLatencyClass,
  CapabilityState,
  CapabilityReadiness,
  ToolCapabilities,
  ToolHints,
  CliHints,
  McpHints,
  PiHints,
  ErrorCode,
  InvocationMetric,
  MetricsSink,
  InMemorySink,
  ToolRegistryOptions,
  InvokeOptions,
  ToolTier,
  ToolApproval,
  ToolApprovalDecision,
  ToolApprovalObject,
  ResolvedApproval,
} from "@gonk/tool-registry";

// ─── @gonk/scope ─────────────────────────────────────────────────────────────
export {
  DEFAULT_ROOT_ORDER,
  DOCUMENT_FILES,
  SCOPE_RESOLUTION_ORDER,
  bindRoots,
  canonical,
  findProjectRoot,
  resolveSessionHome,
  resolveTierHomes,
  scanDocuments,
  scopeStateHome,
  NATIVE_HOST_ROOT_KINDS,
  SUBSTRATE_NS,
  SUBSTRATE_STUB_FILE,
  nativeSubstrateMirror,
  readSubstrateStub,
  resolveNativeSubstrateHome,
  substrateDir,
  writeSubstrateStub,
  adoptNativePersonaSubstrate,
  migrateSubstrateHome,
  FsScopeStore,
  createScope,
  ensureRoot,
  MemoryScopeStore,
  StandardRootAdapter,
  migrateRootToStandardLayout,
  migrateAllUnder,
  resolveStableSessionId,
  sessionMemoryDbPath,
} from "@gonk/scope";
export type {
  BlobHandle,
  DocumentEntry,
  DocumentKind,
  DocumentRole,
  ResolutionEntry,
  RootAdapter,
  RootBinding,
  RootKind,
  ScopeEnvironment,
  ScopeName,
  ScopeStore,
  SetOptions,
  SubstrateMigrationSummary,
  SubstrateMove,
  MigrateOptions,
  MigrationSummary,
  SessionMemoryDbPathOptions,
} from "@gonk/scope";
